postsubmits:
  kubernetes/community:
  - name: post-community-tempelis-apply
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    branches:
    - ^master$
    run_if_changed: '^communication/slack-config'
    annotations:
      testgrid-num-failures-to-alert: "1"
      # TODO: slack admins email group instead?
      testgrid-alert-email: sig-contribex-leads@kubernetes.io
      testgrid-dashboards: sig-contribex-slack-infra
    spec:
      containers:
      - image: gcr.io/k8s-staging-slack-infra/tempelis:v20200909-1eb97f5
        command:
        - /tempelis
        args:
        - --config=communication/slack-config/
        - --restrictions=communication/slack-config/restrictions.yaml
        - --auth=/etc/slack-auth/auth.json
        - --dry-run=false
        volumeMounts:
        - name: tempelis-creds
          mountPath: /etc/slack-auth
          readOnly: true
      volumes:
      - name: tempelis-creds
        secret:
          secretName: slack-tempelis-auth
