presets:
- labels:
    preset-cluster-api-provider-vsphere-e2e-config: "true"
  env:
  - name: BOSKOS_HOST
    value: http://192.168.6.162:32222
  - name: GOVC_URL
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-url
  - name: GOVC_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-cluster-api-provider-vsphere-user
  - name: GOVC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-cluster-api-provider-vsphere-password
  - name: VSPHERE_TLS_THUMBPRINT
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-thumbprint
  - name: VM_SSH_PUB_KEY
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-e2e-vm-ssh.pubkey
  volumeMounts:
  - name: vmc-e2e-vm-ssh-key
    mountPath: /root/ssh/.private-key
  - name: vmc-vpn
    mountPath: /root/.openvpn
  volumes:
  - name: vmc-e2e-vm-ssh-key
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: vmc-e2e-vm-ssh.key
        path: private-key
  - name: vmc-vpn
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: vmc-vpn-config.ovpn
        path: prow.ovpn
      - key: vmc-vpn-client.crt
        path: client.crt
      - key: vmc-vpn-client.key
        path: client.key
      - key: vmc-vpn-ca.crt
        path: ca.crt
      - key: vmc-vpn-tls.key
        path: tls.key
- labels:
    # For kubernetes/cloud-provider-vsphere
    preset-cloud-provider-vsphere-e2e-config-capv: "true"
  env:
  - name: BOSKOS_HOST
    value: http://192.168.6.162:32222
  - name: GOVC_URL
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-url
  - name: GOVC_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-cloud-provider-vsphere-user
  - name: GOVC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-cloud-provider-vsphere-password
  - name: VSPHERE_TLS_THUMBPRINT
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-thumbprint
  - name: VM_SSH_PUB_KEY
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-e2e-vm-ssh.pubkey
  volumeMounts:
  - name: vmc-e2e-vm-ssh-key
    mountPath: /root/ssh/.private-key
  - name: vmc-vpn
    mountPath: /root/.openvpn
  volumes:
  - name: vmc-e2e-vm-ssh-key
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: vmc-e2e-vm-ssh.key
        path: private-key
  - name: vmc-vpn
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: vmc-vpn-config.ovpn
        path: prow.ovpn
      - key: vmc-vpn-client.crt
        path: client.crt
      - key: vmc-vpn-client.key
        path: client.key
      - key: vmc-vpn-ca.crt
        path: ca.crt
      - key: vmc-vpn-tls.key
        path: tls.key
- labels:
    # For kubernetes-sigs/image-builder
    preset-image-builder-vsphere-e2e-config: "true"
  env:
  - name: BOSKOS_HOST
    value: http://192.168.6.162:32222
  - name: GOVC_URL
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-url
  - name: GOVC_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-image-builder-user
  - name: GOVC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-image-builder-password
  - name: VSPHERE_TLS_THUMBPRINT
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-thumbprint
  volumeMounts:
  - name: vmc-vpn
    mountPath: /root/.openvpn
  volumes:
  - name: vmc-vpn
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: vmc-vpn-config.ovpn
        path: prow.ovpn
      - key: vmc-vpn-client.crt
        path: client.crt
      - key: vmc-vpn-client.key
        path: client.key
      - key: vmc-vpn-ca.crt
        path: ca.crt
      - key: vmc-vpn-tls.key
        path: tls.key
- labels:
    preset-cluster-api-provider-vsphere-janitor-config: "true"
  env:
  - name: BOSKOS_HOST
    value: http://192.168.6.162:32222
  - name: GOVC_URL
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-url
  - name: GOVC_USERNAME
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-janitor-user
  - name: GOVC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-janitor-password
  - name: VSPHERE_TLS_THUMBPRINT
    valueFrom:
      secretKeyRef:
        name: cluster-api-provider-vsphere-ci
        key: vmc-vcenter-thumbprint
  volumeMounts:
  - name: vmc-vpn
    mountPath: /root/.openvpn
  volumes:
  - name: vmc-vpn
    secret:
      secretName: cluster-api-provider-vsphere-ci
      defaultMode: 256
      items:
      - key: vmc-vpn-config.ovpn
        path: prow.ovpn
      - key: vmc-vpn-client.crt
        path: client.crt
      - key: vmc-vpn-client.key
        path: client.key
      - key: vmc-vpn-ca.crt
        path: ca.crt
      - key: vmc-vpn-tls.key
        path: tls.key
